name: PR Checks
on: [pull_request]

jobs:
  ai-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: Ostrich-Cyber-Risk/ai-codereviewer@v2.7.1
        with:
          OCTOKIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # ← 正しい入力名
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          root: frontend
