name: PR Checks
on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions: write-all      # PR へコメントを書くため
    steps:
      - uses: actions/checkout@v4

      # Lint & Unit Test
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npm run lint
      - run: npm test

      # AI Code Review (OpenAI)
      - uses: Ostrich-Cyber-Risk/ai-codereviewer@v2.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}