# .github/workflows/pr.yml
name: PR Checks
on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        options: >-
          --health-cmd="pg_isready -U test -d test"
          --health-interval=10s --health-timeout=5s --health-retries=5

    env:
      # ---- DB ----
      PGHOST: localhost
      PGPORT: 5432
      PGUSER:     ${{ secrets.PGUSER_TEST }}
      PGPASSWORD: ${{ secrets.PGPASSWORD_TEST }}
      PGDATABASE: ${{ secrets.PGDB_TEST }}
      DATABASE_URL:  postgresql://${{ secrets.PGUSER_TEST }}:${{ secrets.PGPASSWORD_TEST }}@localhost:5432/${{ secrets.PGDB_TEST }}
      TEST_DATABASE_URL: ${{ env.DATABASE_URL }}   # ← ここは OK（自己参照ではなく上で定義済み）

      # ---- Cloudinary ----
      NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{ vars.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }}
      CLOUDINARY_API_KEY:     ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET:  ${{ secrets.CLOUDINARY_API_SECRET }}

      # ---- R2 ----
      R2_BUCKET:            ${{ vars.R2_BUCKET }}
      R2_ENDPOINT:          ${{ vars.R2_ENDPOINT }}
      R2_ACCESS_KEY_ID:     ${{ secrets.R2_ACCESS_KEY_ID }}
      R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - run: npm ci
      - run: npm run lint
      - run: npm test --runInBand

      - uses: Ostrich-Cyber-Risk/ai-codereviewer@v2.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          root: frontend
