name: PR Checks
on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      test-db:                      # ← ホスト名をアプリに合わせる
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports: [ '5432:5432' ]
        options: >-
          --health-cmd="pg_isready -U test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      PGHOST: test-db              # ← service 名と同じ
      PGUSER: test
      PGPASSWORD: test
      PGDATABASE: test
      PGPORT: 5432
      TEST_MODE: true

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - run: npm ci
      - run: npm run lint
      - run: npm test              # cross-env TEST_MODE=true jest --runInBand

      - uses: Ostrich-Cyber-Risk/ai-codereviewer@v2.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          root: frontend
          exclude: "**/*.md,frontend/.next/**"
